AMAZONAWS:
  id: 4
  credentials:
    username: <your username>
    password: <your password>
  name: Amazon Rekognition
FACEPLUSPLUS:
  id: 6
  credentials:
    username: <your username>
    password: <your password>
  name: Face++
